version: '2.1'

services:
  web:
    build: .
    container_name: nodejs
    env_file: .env
    ports:
    - "3000:3000"
    volumes:
    - .:/usr/src/app
    networks:
      app_net:
        ipv4_address: 192.168.1.196
     
networks:
  app_net :
    driver: bridge
    enable_ipv6: false
    ipam:
      driver: default
      config:
      - subnet: 192.168.1.0/24
        gateway: 192.168.1.254